// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "soong"
#define SECRET_PASS "1771167a"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a32qc196pzw17h-ats.iot.ap-northeast-1.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIIChjCCAW6gAwIBAgIUafCHSdx8WzZvsMBeaqzyv3NCSDowDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTIwNDA0NDQw
OVoXDTQ5MTIzMTIzNTk1OVowFjEUMBIGA1UEAxMLTUtSV2lGaTEwMTAwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAATBY68T/lgmau8pUoIDWc1NKhxfZKTQ/AyPTw/o
9KTSHZgRveIIBV3a/K7/ERxF8fsklNAzYER6jaP1fhowhK31o2AwXjAfBgNVHSME
GDAWgBTZituaZstqETJrGYz4gEu9MPB2ajAdBgNVHQ4EFgQU+/Av7yNWujbL+Vkc
qXeZTaJJbTMwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcN
AQELBQADggEBAEWHtR1ZQNbRx4lnBD+xv2LDS1PFBgIMwLDYVt8JZWYNADxiKWMb
C36auAFq1HPpvK2IO+WbKQ7chjLro0UCDS2XjMyRShGnaCF8/JlHKN3I6mIojTQf
VcST36QHNAi+N62yBVzxyj+sf2twaAq6pGoTIu5KgV5b7R3okgMwuyY8ZTiFBT7r
EBrNxJSwQ1Fo5JqP4VToE6WD2QavThAIAqIzlHgYbtV4fscuPDKFfHUKyoYRxEvs
gqXqJyQPRseLAAeCgMxLc0ZVCyIBlRKVRVijb2avq9EHHptNWiu7asm3IryqB15s
laIeUCwGq0vxdbAaWpb1mp5wxSliPxHQ4ng=
-----END CERTIFICATE-----
)";
